name: MacOS aarch64 release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install JDK 25
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 25
        check-latest: true
        cache: 'maven'
    - name: Build native executable
      run: mvn clean package -Dnative -Dmaven.repo.local=/tmp
    - name: Get version
      shell: bash -l {0}
      run: echo project_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_ENV
    - name: Upload native executable
      id: upload-native-executable
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./target/test-failure-detector-${{env.project_version}}-runner
        asset_name: test-failure-detector-macos-aarch64
        asset_content_type: application/octet-stream
